### ISSUE TITLE
Investigate and fix ignored exceptions and unclosed files

### ISSUE THREAD

**Issue by lxp** [cfv-project/cfv#58]
Tests fail when treating all Python warnings as errors.

```
>>> testing...
.....................
>>> failed test: /home/runner/work/cfv/cfv/test/cfv -ZNVRMUI --unquote=no --fixpaths="" --strippaths=0 --showpaths=auto-relative --progress=no --announceurl=url --noprivate_torrent -r -p /tmp/tmpmjh48zao --showpaths=0 -q -T --list0=bad 
Exception ignored in: <_io.FileIO name='d2.sha512' mode='rb' closefd=True>
Traceback (most recent call last):
  File "/home/runner/work/cfv/cfv/lib/cfv/common.py", line 1349, in <module>
    class SFV(SFV_Base, CRC_MixIn):
ResourceWarning: unclosed file <_io.FileIO name='d2.sha512' mode='rb' closefd=True>
Exception ignored in: <_io.FileIO name='tmpmjh48zao.sha512' mode='rb' closefd=True>
Traceback (most recent call last):
  File "/home/runner/work/cfv/cfv/lib/cfv/common.py", line 1349, in <module>
    class SFV(SFV_Base, CRC_MixIn):
ResourceWarning: unclosed file <_io.FileIO name='tmpmjh48zao.sha512' mode='rb' closefd=True>
Exception ignored in: <_io.FileIO name='test4.foo' mode='rb' closefd=True>
Traceback (most recent call last):
  File "/home/runner/work/cfv/cfv/lib/cfv/hash.py", line 77, in <lambda>
    return lambda filename, callback: _getfilechecksum(filename, hasher, callback), hasher().digest_size
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ResourceWarning: unclosed file <_io.BufferedReader name='test4.foo'>
test4.fooException ignored in: <_io.FileIO name='test.ext.end' mode='rb' closefd=True>
Traceback (most recent call last):
  File "/home/runner/work/cfv/cfv/lib/cfv/hash.py", line 77, in <lambda>
    return lambda filename, callback: _getfilechecksum(filename, hasher, callback), hasher().digest_size
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ResourceWarning: unclosed file <_io.BufferedReader name='test.ext.end'>
test.ext.endException ignored in: <_io.FileIO name='test2.foo' mode='rb' closefd=True>
Traceback (most recent call last):
  File "/home/runner/work/cfv/cfv/lib/cfv/hash.py", line 77, in <lambda>
    return lambda filename, callback: _getfilechecksum(filename, hasher, callback), hasher().digest_size
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ResourceWarning: unclosed file <_io.BufferedReader name='test2.foo'>
test2.fooException ignored in: <_io.FileIO name='test3' mode='rb' closefd=True>
Traceback (most recent call last):
  File "/home/runner/work/cfv/cfv/lib/cfv/hash.py", line 77, in <lambda>
    return lambda filename, callback: _getfilechecksum(filename, hasher, callback), hasher().digest_size
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ResourceWarning: unclosed file <_io.BufferedReader name='test3'>
test3
FAILED (2)
  File "/home/runner/work/cfv/cfv/test/test.py", line 1884, in <module>
    failed += all_tests()

  File "/home/runner/work/cfv/cfv/test/test.py", line 1622, in all_tests
    ren_test(fmt)

  File "/home/runner/work/cfv/cfv/test/test.py", line 905, in ren_test
    test_generic(basecmd + ' --showpaths=0 -q -T --list0=bad', cfv_listdata_bad_test)

  File "/home/runner/work/cfv/cfv/test/test.py", line 269, in test_generic
    test_log_results(cfvtest.cfvenv + cfvtest.cfvfn + ' ' + cmd, s, o, r, kw)

  File "/home/runner/work/cfv/cfv/test/test.py", line 254, in test_log_results
    test_log_finish(cmd, s, r, o, kw)

  File "/home/runner/work/cfv/cfv/test/test.py", line 237, in test_log_finish
    traceback_str = '\n'.join(traceback.format_stack())

Exception ignored in: <_io.FileIO name='d2.sha512' mode='rb' closefd=True>
ResourceWarning: unclosed file <_io.FileIO name='d2.sha512' mode='rb' closefd=True>
Exception ignored in: <_io.FileIO name='tmpmjh48zao.sha512' mode='rb' closefd=True>
ResourceWarning: unclosed file <_io.FileIO name='tmpmjh48zao.sha512' mode='rb' closefd=True>
Exception ignored in: <_io.FileIO name='/tmp/cfv_3.0.1.dev0_test-20240518T103311.log' mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/cfv_3.0.1.dev0_test-20240518T103311.log' mode='wt' encoding='UTF-8'>
```

**Comment by lxp** [comment]
Fixed by #56
